# docker-compose config

version: '2'
services:
  devserver:
    build:
      context: ./server/
    ports:
      - "8080:8080"

  devclient:
    build:
      context: ./client/
    ports:
      - "3000:3000"
    depends_on:
      - devserver
    links:
      - "devserver:devserver"
